[package]
name = "mirc"
version = "0.1.10"
edition = "2021"
authors = ["wpbirney <wpb@360scada.com"]
description = "Simple mirc color formatting for irc clients"
license = "MIT"
readme = "readme.md"
repository = "https://github.com/wpbirney/mirc-rs"

[dependencies]
